
["Biome Generation Weight"]
	#Generation weight of Shallow Ocean
	#Range: 0 ~ 1000
	shallow_ocean_generation_weight = 1
	#Generation weight of Plastic Ocean
	#Range: 0 ~ 1000
	plastic_ocean_generation_weight = 1
	#Generation weight of Hot Ocean
	#Range: 0 ~ 1000
	hot_ocean_generation_weight = 1

["Jungle Fighters Spawn Weight"]
	#Spawn weight of Piranha
	#Range: 0 ~ 1000
	piranha_spawn_weight = 70
	#Spawn weight of Junge Blowfish
	#Range: 0 ~ 1000
	jungle_blowfish_spawn_weight = 40
	#Spawn weight of Tigerfish
	#Range: 0 ~ 1000
	tigerfish_spawn_weight = 40
	#Spawn weight of Arapaima
	#Range: 0 ~ 1000
	arapaima_spawn_weight = 70

["River Warriors Spawn Weight"]
	#Spawn weight of Triop
	#Range: 0 ~ 1000
	triop_spawn_weight = 30
	#Spawn weight of RiverShark
	#Range: 0 ~ 1000
	rivershark_spawn_weight = 10
	#Spawn weight of Tilapia
	#Range: 0 ~ 1000
	tilapia_spawn_weight = 70
	#Spawn weight of Fat Carp
	#Range: 0 ~ 1000
	fat_carp_spawn_weight = 30
	#Spawn weight of Toe Biter
	#Range: 0 ~ 1000
	toe_biter_spawn_weight = 30
	#Spawn weight of Plecostomus
	#Range: 0 ~ 1000
	plecostomus_spawn_weight = 30
	#Spawn weight of Paddlefish
	#Range: 0 ~ 1000
	paddlefish_spawn_weight = 50

["Swamp Knights Spawn Weight"]
	#Spawn weight of Giant Stingrays
	#Range: 0 ~ 1000
	giant_stingray_spawn_weight = 5
	#Spawn weight of Goliath Catfish
	#Range: 0 ~ 1000
	goliath_catfish_spawn_weight = 5

["Icy Soldiers Spawn Weight"]
	#Spawn weight of Beluga Sturgeon
	#Range: 0 ~ 1000
	beluga_sturgeon_spawn_weight = 90

["Deep Sea Livers Spawn Weight"]
	#Spawn weight of Coelacanth
	#Range: 0 ~ 1000
	coelacanth_spawn_weight = 10
	#Spawn weight of Goblin Shark
	#Range: 0 ~ 1000
	goblin_shark_spawn_weight = 10
	#Spawn weight of Yeti Crab
	#Range: 0 ~ 1000
	yeti_crab_spawn_weight = 40
	#Spawn weight of Tripod Fish
	#Range: 0 ~ 1000
	tripod_fish_spawn_weight = 10
	#Spawn weight of Hatchet Fish
	#Range: 0 ~ 1000
	hatchet_fish_spawn_weight = 10
	#Spawn weight of Oarfish
	#Range: 0 ~ 1000
	oarfish_spawn_weight = 10
	#Spawn weight of Football Fish
	#Range: 0 ~ 1000
	football_fish_spawn_weight = 20
	#Spawn weight of Spider Crab
	#Range: 0 ~ 1000
	spider_crab_spawn_weight = 10

["Cold Ocean Titans Spawn Weight"]
	#Spawn weight of Salmon Shark
	#Range: 0 ~ 1000
	salmon_shark_spawn_weight = 10
	#Spawn weight of Mahi Mahi
	#Range: 0 ~ 1000
	mahi_mahi_spawn_weight = 10
	#Spawn weight of Sea Spider
	#Range: 0 ~ 1000
	sea_spider_spawn_weight = 10
	#Spawn weight of Bigfin Squid
	#Range: 0 ~ 1000
	bigfin_squid_spawn_weight = 10
	#Spawn weight of Ice Fish
	#Range: 0 ~ 1000
	ice_fish_spawn_weight = 10
	#Spawn weight of Slender Sunfish
	#Range: 0 ~ 1000
	slender_sunfish_spawn_weight = 10
	#Spawn weight of Marlin
	#Range: 0 ~ 1000
	marlin_spawn_weight = 10
	#Spawn weight of Mola Mola
	#Range: 0 ~ 1000
	mola_mola_spawn_weight = 10
	#Spawn weight of Lion Mane Jellyfish
	#Range: 0 ~ 1000
	lion_mane_jellyfish_spawn_weight = 10
	#Spawn weight of Basking Shark
	#Range: 0 ~ 1000
	basking_shark_spawn_weight = 10
	#Spawn weight of Snail Fish
	#Range: 0 ~ 1000
	snail_fish_spawn_weight = 10
	#Spawn weight of Sleeper Shark
	#Range: 0 ~ 1000
	sleeper_shark_spawn_weight = 10

["Warm Stayers Spawn Weight"]
	#Spawn weight of Reef Goby
	#Range: 0 ~ 1000
	reef_goby_spawn_weight = 30
	#Spawn weight of Sea Horse
	#Range: 0 ~ 1000
	sea_horse_spawn_weight = 30
	#Spawn weight of Giant Starfish
	#Range: 0 ~ 1000
	giant_starfish_spawn_weight = 10
	#Spawn weight of Box Fish
	#Range: 0 ~ 1000
	box_fish_spawn_weight = 30
	#Spawn weight of Rockfish
	#Range: 0 ~ 1000
	rockfish_spawn_weight = 10
	#Spawn weight of Royal Gramma
	#Range: 0 ~ 1000
	royal_gramma_spawn_weight = 30
	#Spawn weight of Starfish
	#Range: 0 ~ 1000
	starfish_spawn_weight = 20
	#Spawn weight of Rough Shark
	#Range: 0 ~ 1000
	rough_shark_spawn_weight = 30
	#Spawn weight of Goliath Grouper
	#Range: 0 ~ 1000
	goliath_grouper_spawn_weight = 40
	#Spawn weight of Moray Eel
	#Range: 0 ~ 1000
	moray_eel_spawn_weight = 10
	#Spawn weight of Eagle Ray
	#Range: 0 ~ 1000
	eagle_ray_spawn_weight = 40
	#Spawn weight of Angelfish
	#Range: 0 ~ 1000
	angelfish_spawn_weight = 30
	#Spawn weight of Foxface Fish
	#Range: 0 ~ 1000
	foxface_fish_spawn_weight = 30
	#Spawn weight of Lemon Shark
	#Range: 0 ~ 1000
	lemon_shark_spawn_weight = 30
	#Spawn weight of Wobbegong
	#Range: 0 ~ 1000
	wobbegong_spawn_weight = 30

["Beach Dwellers Spawn Weight"]
	#Spawn weight of Sea Skater
	#Range: 0 ~ 1000
	sea_skate_spawn_weight = 50
	#Spawn weight of Man O War
	#Range: 0 ~ 1000
	man_o_war_spawn_weight = 50
	#Spawn weight of Cow Nose Ray
	#Range: 0 ~ 1000
	cow_nose_ray_spawn_weight = 50
	#Spawn weight of Guitar Shark
	#Range: 0 ~ 1000
	guitar_shark_spawn_weight = 50
	#Spawn weight of Sea Urchin
	#Range: 0 ~ 1000
	sea_urchin_spawn_weight = 50
	#Spawn weight of SpongeBob
	#Range: 0 ~ 1000
	spongebob_spawn_weight = 50
	#Spawn weight of Dumbo Octopus
	#Range: 0 ~ 1000
	dumbo_octopus_spawn_weight = 50
	#Spawn weight of HorseShoe Crab
	#Range: 0 ~ 1000
	horseshoe_crab_spawn_weight = 70
	#Spawn weight of Coconut Crab
	#Range: 0 ~ 1000
	coconut_crab_spawn_weight = 50
	#Spawn weight of Sea Cucumber
	#Range: 0 ~ 1000
	sea_cucumber_spawn_weight = 50
	#Spawn weight of Bull Shark
	#Range: 0 ~ 1000
	bull_shark_spawn_weight = 50

