#Can the watering cans spread grass faster
canSpreadGrass = true
#The refill rate of water/tick
#Default: 30
#Range: 1 ~ 100000
refillRate = 30
#Moisturize farm land
moisturize = true

[wateringcan]

	[wateringcan.diamond]
		#The chance to further a growth stage
		#Range: 1 ~ 100
		chance = 35
		#Use water at all, or have it be infinite use
		#Default: true
		useWater = true
		#The amount of water consumed per tick
		#Range: 1 ~ 10000
		drainRate = 10
		#The maximum amount of water the watering can can hold
		#Range: 100 ~ 100000
		maxWater = 10000
		#Auto harvest fully grown crops
		#Default: false
		autoHarvest = false
		#The radius of effect for the watering can
		#Number MUST be uneven
		#Default: 5
		#Range: 1 ~ 15
		radius = 5

	[wateringcan.aquamarine]
		#The chance to further a growth stage
		#Range: 1 ~ 100
		chance = 65
		#Use water at all, or have it be infinite use
		#Default: false
		useWater = false
		#The amount of water consumed per tick
		#Range: 1 ~ 10000
		drainRate = 1
		#The maximum amount of water the watering can can hold
		#Range: 100 ~ 100000
		maxWater = 10000
		#Auto harvest fully grown crops
		#Default: true
		autoHarvest = true
		#The radius of effect for the watering can
		#Number MUST be uneven
		#Default: 9
		#Range: 1 ~ 15
		radius = 9

	[wateringcan.copper]
		#The chance to further a growth stage
		#Range: 1 ~ 100
		chance = 15
		#Use water at all, or have it be infinite use
		#Default: true
		useWater = true
		#The amount of water consumed per tick
		#Range: 1 ~ 10000
		drainRate = 5
		#The maximum amount of water the watering can can hold
		#Range: 100 ~ 100000
		maxWater = 2000
		#Auto harvest fully grown crops
		#Default: false
		autoHarvest = false
		#The radius of effect for the watering can
		#Number MUST be uneven
		#Default: 3
		#Range: 1 ~ 15
		radius = 3

	[wateringcan.quartz]
		#The chance to further a growth stage
		#Range: 1 ~ 100
		chance = 25
		#Use water at all, or have it be infinite use
		#Default: true
		useWater = true
		#The amount of water consumed per tick
		#Range: 1 ~ 10000
		drainRate = 5
		#The maximum amount of water the watering can can hold
		#Range: 100 ~ 100000
		maxWater = 5000
		#Auto harvest fully grown crops
		#Default: false
		autoHarvest = false
		#The radius of effect for the watering can
		#Number MUST be uneven
		#Default: 3
		#Range: 1 ~ 15
		radius = 3

	[wateringcan.ender]
		#The chance to further a growth stage
		#Range: 1 ~ 100
		chance = 45
		#Use water at all, or have it be infinite use
		#Default: true
		useWater = true
		#The amount of water consumed per tick
		#Range: 1 ~ 10000
		drainRate = 1
		#The maximum amount of water the watering can can hold
		#Range: 100 ~ 100000
		maxWater = 10000
		#Auto harvest fully grown crops
		#Default: true
		autoHarvest = false
		#The radius of effect for the watering can
		#Number MUST be uneven
		#Default: 7
		#Range: 1 ~ 15
		radius = 7

	[wateringcan.basic]
		#The chance to further a growth stage
		#Range: 1 ~ 100
		chance = 10
		#Use water at all, or have it be infinite use
		#Default: true
		useWater = true
		#The amount of water consumed per tick
		#Range: 1 ~ 10000
		drainRate = 5
		#The maximum amount of water the watering can can hold
		#Range: 100 ~ 100000
		maxWater = 1000
		#Auto harvest fully grown crops
		#Default: false
		autoHarvest = false
		#The radius of effect for the watering can
		#Number MUST be uneven
		#Default: 3
		#Range: 1 ~ 15
		radius = 3

